### ISSUE TITLE
Still problems with creating local instance of the kendo plugin

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#70]
1. Completely obliterated the npm, jspm caches and instances.
2. Reinstalled the jspm, jspm-git and bower "globally"
3. Made a fresh clone of the plugin and verified that package.json has references to Aurelia Beta 1
4. Then:
```
cd C:\work\aurelia-ui-toolkits\aurelia-kendoui-plugin
npm install
```
5. These went fine - and at this point (before you started this jspm-git trick) I would run 
```
jspm install
```
and that would install all aurelia.

6. Now I get this:
```
λ jspm install                                                                               
                                                                                             
err  TypeError: must start with number, buffer, array or string                              
         at fromObject (buffer.js:158:9)                                                     
         at new Buffer (buffer.js:57:10)                                                     
         at decodeCredentials (C:\work\aurelia-ui-toolkits\aurelia-kendoui-plugin\node_module
s\jspm-git\git.js:56:14)                                                                     
         at Object.GitLocation (C:\work\aurelia-ui-toolkits\aurelia-kendoui-plugin\node_modul
es\jspm-git\git.js:239:17)                                                                   
         at Object.exports.load (C:\work\aurelia-ui-toolkits\aurelia-kendoui-plugin\node_modu
les\jspm\lib\registry.js:73:56)                                                              
         at new RegistryPath (C:\work\aurelia-ui-toolkits\aurelia-kendoui-plugin\node_modules
\jspm\lib\config\loader.js:261:33)                                                           
         at Config.read (C:\work\aurelia-ui-toolkits\aurelia-kendoui-plugin\node_modules\jspm
\lib\config\loader.js:126:26)                                                                
         at C:\work\aurelia-ui-toolkits\aurelia-kendoui-plugin\node_modules\jspm\lib\config.j
s:100:26                                                                                     
         at process._tickCallback (node.js:356:9)                                            
         at Function.Module.runMain (module.js:477:11)                                       
                                                                                             
err  Unable to load registry kendo                                                           
                                                                                             
warn Installation changes not saved.
```
WOW

**Comment by adriatic** [comment]
As I learned the hard way, **steps I took** to start from a clean slate, trying to remove the use of `jspm-git` - **are incomplete**. In addition to clearing all of the caches, and proper editing the `package.json` file to remove the references to `jspm-git` as well as **references to bower endpoints** that require the use of `jspm-git`, there is still a place where old "settings" remain persistent - `config.js` (both at the root and sample levels)

This in a sense should not be a surprise - as it is a perfect example of the dangers of keeping redundant information in the system. I believed that `config.js` file, produced by jspm by reading the `package.json` file will **always** represent the state of `package.json` file. 

Lesson learned: after changing the `package.json` file, delete the `config.js` file, have jspm regenerate the it, and then remember to manually add the aurelia specific babelOptions:
```
babelOptions: {
    "optional": [
      "es7.decorators",
      "es7.classProperties"
    ]
  },
```

**Comment by adriatic** [comment]
See https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/71
