### ISSUE TITLE
Create the Aurelia Beta 1 compatible plugin version

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#72]
This task directly references https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/71 which in turn relates to several previous tasks, where all are superseded with this one.

I am proposing to have Charles deal with
1.1 [root level package.json](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/package.json)
1.2 [sample level package.json](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/package.json)
1.3 [sample level index.html](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/index.html)

where 1.1 and 1.2 are trivial and already done at several place.

The issue 1.3 requires some care as the section 
```
      // Load the package.json from the root to get the package name
      System.import("root/package.json!").then(function(m) {
        var cfg = {
           packages: {}
        };
        // Create a new systemjs package with the package name
        cfg.packages[m.name] = {
            "main": "index",
              "dependencies": {
                "aurelia-binding": "github:aurelia/binding@^0.10.2",
                "aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.11.2",
                "aurelia-templating": "github:aurelia/templating@^0.16.0"
              }
            };
``` 

not only requires the correct references to Aurelia, but also to the line
```
System.import("root/package.json!").then(function(m) {
```
as it seems that "root/package.json!" needs not to be changed to "package.json! . I may be wrong here - so please verify and fix as needed, as even with this code:

```
   <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
      System.import('aurelia-bootstrapper');

      // Load the package.json from the root to get the package name
      System.import("package.json!").then(function(m) {
        var cfg = {
           packages: {}
        };

        // Create a new systemjs package with the package name
        cfg.packages[m.name] = {
            "main": "index",
              "dependencies": {
                "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.0.1",
                "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
                "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1"
              }
            };

        System.config(cfg);

      });

    </script>
```

(these changes being done on my local repo) I get this:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/jspm_packages/npm/core-js@1.2.6/modules/es6.promise.js:107 Error: XHR error (404 Not Found) loading http://localhost:3000/main.js
	Error loading http://localhost:3000/main.js
    at o (http://localhost:3000/jspm_packages/system.js:4:12694)
    at XMLHttpRequest.s.onreadystatechange (http://localhost:3000/jspm_packages/system.js:4:13219)run @ :3000/jspm_packages/npm/core-js@1.2.6/modules/es6.promise.js:107
```

**Comment by charlespockert** [comment]
Nope, the root level `package.json` should be referenced from the root as it's setup

The root level `package.json` contains the install information for users installing the plugin; this includes the plugin name which is used to load the plugin in the sample app and create an ad-hoc package which wraps the plugin.

**Comment by adriatic** [comment]
I believe that the original code is **not correct** as it does not reference the Beta 1 Aurelia components. So, when I fix the references to Aurelia 

```
<!doctype html>
<html>
  <head>
    <title>Aurelia</title>
    <link rel="stylesheet" href="jspm_packages/npm/font-awesome@4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/styles/default.min.css">
    <link rel="stylesheet" href="styles.css">

    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/highlight.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body aurelia-app="main">
    <div class="splash">
      <div class="message">Aurelia Kendo Samples</div>
      <i class="fa fa-spinner fa-spin"></i>
    </div>

    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
      System.import('aurelia-bootstrapper');

      // Load the package.json from the root to get the package name
      System.import("root/package.json!").then(function(m) {
        var cfg = {
           packages: {}
        };

        // Create a new systemjs package with the package name
        cfg.packages[m.name] = {
            "main": "index",
              "dependencies": {
                "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.0.1",
                "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
                "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1"
              }
            };

        System.config(cfg);

      });

    </script>
  </body>
</html>

```

and run the app, I get (**note that it cannot find the `package.json`**)

```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:3000/root/package.json(…)
http://localhost:3000/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/main.js Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/jspm_packages/npm/core-js@1.2.6/modules/es6.promise.js:107 Error: XHR error (404 Not Found) loading http://localhost:3000/main.js(…)run @ :3000/jspm_packages/npm/core-js@1.2.6/modules/es6.promise.js:107
```

**Comment by charlespockert** [comment]
Actually the dependencies should be those for the plugin:

```
 System.import("root/package.json!").then(function(m) {
        var cfg = {
           packages: {}
        };

        // Create a new systemjs package with the package name
        cfg.packages[m.name] = {
            "main": "index",
              "dependencies": m.jspm.dependencies
            };

        System.config(cfg);

      });
```

Still not sure why you have an error, mine is working fine

**Comment by adriatic** [comment]
Note that the ["official code" in the repo](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/index.html#L30-L37) matches what I just shared with you. So, if your local copy matches what you just wrote above, I would not be surprised that my code fails and your works :-)

**Comment by charlespockert** [comment]
Yeah, it's an artefact from when I was trying to get it all setup, it should work fine either way assuming the libraries are there

Will update soon!

**Comment by adriatic** [comment]
My proposal is simple: act as owning the whole world and bring the https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin repo to the level you see appropriate. Then I can make a clone and see whether all this works for me as well

**Comment by JeroenVinke** [comment]
@adriatic Since the plugin (and sample) is now updated to use the beta of Aurelia, I assume we can close this? We can always evaluate switching the sample app back to jspm-git after we fixed the issues mentioned in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/78

**Comment by adriatic** [comment]
Agreed - closing it
